{% set name = "cmdstanpy" %}
{% set version = "1.2.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/stan-dev/cmdstanpy/archive/v{{ version }}.tar.gz
  sha256: 0f0ff304f40740d168956f2343e95f9af6c9fba5b50d49683bcb95dc2278a46e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - install_cmdstan = cmdstanpy.install_cmdstan:main
    - install_cxx_toolchain = cmdstanpy.install_cxx_toolchain:main

requirements:
  host:
    - pip
    - setuptools
    - python >=3.8
  run:
    - python >=3.8
    - pandas
    - numpy >=1.21
    - cmdstan
    - tqdm
    - stanio >=0.4.0,<2.0.0


about:
  home: https://mc-stan.org/users/interfaces/cmdstan.html
  dev_url: https://github.com/stan-dev/cmdstanpy
  doc_url: https://cmdstanpy.readthedocs.io
  summary: |
    CmdStanPy is a lightweight interface to Stan for Python users which
    provides the necessary objects and functions to compile a Stan program
    and fit the model to data using CmdStan.
  license: BSD-3-Clause
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - maresb
    - WardBrian
